### ISSUE TITLE
Bug ao rodar o codigo com matriz

### ISSUE THREAD

**Issue by aquila0101** [DesignLiquido/portugol-studio#13]
Tentei rodar esse código na extensão e deu erro no portugol studio funcionou normal

```
programa
{
    funcao inicio()
    {
        //Declaração de uma matriz de inteiros
        // de duas linhas e duas colunas já inicializado.
        inteiro matriz[2][2] = {{15,22},{10,11}}

        //Atribui -1 na primeira linha e segunda
        // coluna da matriz.
        matriz[0][1] = -1

        //Imprime o valor 15 correspondente  
        // a primeira linha e primeira coluna da matriz.
        inteiro i = 0
        escreva(matriz[i][0])
        escreva("\n")

        //Imprime o valor 11 correspondente  
        // a última linha e última coluna da matriz.
        escreva(matriz[1][1])

        //Declaração de uma matriz de reais de 
        // duas linhas e quatro colunas.
        real outra_matriz[2][4]

        //Declaração de uma matriz de caracteres onde o tamanho
        // de linhas e colunas são definidos pela inicialização
        caracter jogo_velha[][] = {{'X','O','X'}
                                  ,{'O','X','O'}
                                  ,{' ',' ','X'}}

    }
}
```
![Captura de tela de 2024-04-07 17-20-05](https://github.com/DesignLiquido/portugol-studio/assets/162712945/f2d44389-4b9f-4ed5-9150-5801ef6762fa)

![Captura de tela de 2024-04-07 17-19
![Captura de tela de 2024-04-07 17-19-32](https://github.com/DesignLiquido/portugol-studio/assets/162712945/6a92fb05-a309-4e60-b90b-506a05db2393)
-07](https://github.com/DesignLiquido/portugol-studio/assets/162712945/7de022b2-c3ab-463a-9cb2-740afd222f93)

**Comment by leonelsanchesdasilva** [comment]
@aquila0101 Este vai levar algum tempo. Estou trabalhando neste branch: https://github.com/DesignLiquido/portugol-studio/tree/bug-matrizes

**Comment by aquila0101** [comment]
@leonelsanchesdasilva tem outro bug quando calculo a sequencia de Fibonacci vou colocar o código aqui mais tarde
