### ISSUE TITLE
erro ao tentar rodar o seguinte codigo

### ISSUE THREAD

**Issue by aquila0101** [DesignLiquido/portugol-studio#15]
Erro na extensão ao rodar o seguinte código:

```
programa
{
	funcao inicio()
	{
		
		cadeia nome[] = { "João", "Ana" , "Tiago", "Luiz", "Carlos" }
		real altura[] = { 5.7, 8.8, 9.75, 1.32, 9.93 }

		// Cria o cabeçalho da tabela
		escreva ("--------------------\n")
		escreva ("       TABELA       \n")
		escreva ("--------------------\n")

			  
		para (inteiro posicao = 0; posicao < 5; posicao++)
		{
			
			escreva (nome[posicao], "\t\t", altura [posicao], "\n")
		}
	}
}
```
![Captura de tela de 2024-04-10 22-32-40](https://github.com/DesignLiquido/portugol-studio/assets/162712945/0be7b88e-69fb-4099-8677-281be51165bc)
![Captura de tela de 2024-04-10 22-33-33](https://github.com/DesignLiquido/portugol-studio/assets/162712945/9d8a6217-87cf-4aef-88ed-05de45352630)

**Comment by leonelsanchesdasilva** [comment]
Corrigido em https://github.com/DesignLiquido/portugol-studio/commit/4fd111e1b4af02ec5bc3992a7f7e17ab65827c79. Favor aguardar a publicação da versão 0.10.22 da extensão.
