### ISSUE TITLE
Erro ao rodar esse código

### ISSUE THREAD

**Issue by aquila0101** [DesignLiquido/portugol-studio#21]
Quando tentei rodar esse código simplesmente não apareceu nada na tela

```
programa
{
	inclua biblioteca Util --> util
	
	funcao inicio() 
	{
		inteiro vetor[10]
		
		// preenche o vetor
		para (inteiro posicao = 0; posicao < 10; posicao++)
		{
			vetor[posicao] = util.sorteia(1, 100) // Sorteia um número e atribui à posição do vetor
		}

		// Exibe o vetor na ordem original
		escreva ("Vetor na ordem original:\n")
		
		para(inteiro posicao = 0; posicao < 10; posicao++)
		{
			escreva (vetor[posicao], " ")
		}
		
		// Exibe o vetor na ordem inversa
		escreva ("\n\nVetor na ordem inversa:\n")
		
		para(inteiro posicao = 9; posicao >=0; posicao--)
		{
			escreva (vetor[posicao], " ")
		}
	}
}

```

**Comment by leonelsanchesdasilva** [comment]
@aquila0101 A partir da versão 0.12.0, a saída fica num novo painel, chamado "Entrada e Saída". Certifique-se de que o painel está aberto antes de executar:

![image](https://github.com/DesignLiquido/portugol-studio/assets/53848829/a39b0730-0cab-4cf3-9da7-6278c30d8434)

De fato, tem um pequeno bug na extensão, conforme a imagem: o painel não está considerando o `\n` como uma quebra de linha. Abri uma issue correspondente para isso. https://github.com/DesignLiquido/vscode/issues/61

Considero que esta issue pode ser fechada.

**Comment by aquila0101** [comment]
Quando rodei esse código na extensão não apareceu nada, por isso tinha reportado obrigado
