### ISSUE TITLE
[Portugol Studio] Erro ao definir número de posições em um vetor usando uma variável ao invés de um número inteiro

### ISSUE THREAD

**Issue by jailsonmartinsfilho** [DesignLiquido/portugol-studio#26]
```
programa {
  funcao inicio() {
    inteiro numeros = 3
    inteiro listaNumeros[numeros]

    escreva(listaNumeros)
  }
}
```
Saída esperada: undefined,undefined,undefined
Erro: Esperado o fechamento de identificação de número  de posições de uma dimensão de vetor ou matriz.

![asdasd](https://github.com/DesignLiquido/portugol-studio/assets/112786570/bba66873-7437-44dc-b95d-54a2574c759e)

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/portugol-studio/releases/tag/0.2.5. Favor aguardar o lançamento da versão 0.12.4 da extensão para novos testes.
