### ISSUE TITLE
Palavra reservada não reconhecida pela extensão

### ISSUE THREAD

**Issue by Arisuup** [DesignLiquido/portugol-studio#28]
A sintaxe "entao", por algum motivo, que eu desconheço, não está sendo reconhecida como uma palavra reservada, e sim como uma variável ao utiliza-lá. Além de que, quando eu tento atribuir a uma variável o tipo logico, também não é reconhecida como uma palavra reservada, e tem o mesmo fim que a outra.  
![Provas](https://github.com/DesignLiquido/portugol-studio/assets/172440472/85d19745-f3c3-4ecd-8b30-f50344eb7bce)

![image](https://github.com/DesignLiquido/portugol-studio/assets/172440472/3a84f83b-8228-4b17-b67b-36298d4dda81)

**Comment by leonelsanchesdasilva** [comment]
Aparentemente a palavra `entao` também não funciona no editor original (exemplo 1):

![image](https://github.com/DesignLiquido/portugol-studio/assets/53848829/b9dc54a3-f4a7-4c68-b857-65cbb8aef212)

Tem certeza de que este código está correto?

Para o exemplo 2, creio estar faltando dois símbolos de fechamento de chaves.

**Comment by Arisuup** [comment]
@leonelsanchesdasilva Independe se há fechamentos ou não, o tipo logico não é reconhecido

**Comment by leonelsanchesdasilva** [comment]
> @leonelsanchesdasilva Independe se há fechamentos ou não, o tipo logico não é reconhecido

É reconhecido sim. Fiz essa imagem com a versão atual da extensão.

![image](https://github.com/DesignLiquido/portugol-studio/assets/53848829/13d449ba-521f-48b6-be28-cf2ab82e607c)

**Comment by samuelrvg** [comment]
@Arisuup A atribuição do tipo lógico não pode ter caractere Maiúsculo, por esse motivo esta gerando erro.

Se fizer o mesmo teste no próprio Portugol Studio, vai ver o mesmo resultado.

https://portugol.dev

![image](https://github.com/DesignLiquido/portugol-studio/assets/14062631/9d6505c1-39f7-4ca8-be1d-2d27439a5de5)

![image](https://github.com/DesignLiquido/portugol-studio/assets/14062631/31bb0fb5-40e7-4805-b93e-0ed3329d699a)

Em relação ao `então` é o que o Leonel mencionou logo acima.

Por enquanto estou encerrando essa ISSUE, qualquer dúvida pode reabrir para discutirmos sobre.
