### ISSUE TITLE
erro na atribuicao de valores

### ISSUE THREAD

**Issue by Aristidescosta** [DesignLiquido/portugol-studio#31]
Ao executar o seguinte código, o programa simplesmente funciona, embora que tem um erro, que é a tipagem da variável

```
programa 
{ 
  funcao inicio () 
  {
    caracter message
    message = "olá mundo"
    escreva(message)
  } 
}
```

Resposta atual é : `olá mundo`
Sendo que deveria gerar um erro como o seguinte:
`Não é possível atribuir um valor do tipo 'cadeia' a uma variável do tipo 'caracter' (linha 10, posição 4)` - `(refêrencia tirada do portugol studio)`

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva  

```
import { TIPO_NATIVO, TipoInferencia } from "../interpretador";
export interface VariavelInterface {
    valor: any;
    tipo: TipoInferencia | TIPO_NATIVO;
    subtipo?: 'texto' | 'número' | 'longo' | 'lógico';
    imutavel: boolean;
    nomeReferencia?: string;
}
```

`export type TipoInferencia = "texto" | "número" | "longo" | "vetor" | "dicionário" | "nulo" | "lógico" | "função" | "símbolo" | "objeto" | "módulo";`

Acredito que o tipo de inferenciador esteja errado, isto porque os tipos não combinam com os do Portugol Studio

Além de que, este `TipoInferencia` vem do `núcleo` do `Delegua`. 
Acredito que não seja a tipagem correcta, esperarei pela resposta do `Sr. Leonel` quanto a esse assunto.

**Comment by leonelsanchesdasilva** [comment]
@Aristidescosta Podes implementar novos tipos, e sobrescrever todos os lugares que usam os tipos de Delégua.

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva  poderia adicionar o tag `hacktoberfest`???

**Comment by leonelsanchesdasilva** [comment]
@Aristidescosta Atualizei todos os nossos pacotes para terem o topic `hacktoberfest`.

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva Mas não consigo ver...

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva 
```
programa
{
    funcao inicio()
    {
        caracter test
        leia(test)
        escreva(test)
    }
}
```

Estou agora a ver, a resolução deste erro vai fazer com que eu ajustes outros arquivos, isto porque no caso do exemplo se eu digitar `Olá mundo` o que deverá ser retornado é `O`, mas atualmente ele retorna toda a string

**Comment by leonelsanchesdasilva** [comment]
Resolvido por https://github.com/DesignLiquido/portugol-studio/pull/34.
